### ISSUE TITLE
Dose not support html-webpack-plugin 5.5.4

### ISSUE THREAD

**Issue by wangzhengbo** [Cheng0639/react-app-rewired-html-webpack-plugin#9]
Dose not support html-webpack-plugin 5.5.4, because html-webpack-plugin 5.5.4 changed it's constructor method.

**Comment by Cheng0639** [comment]
Hi, I'm not sure what the difference is between the constructor for [v5.54](https://github.com/jantimon/html-webpack-plugin/blob/v5.5.4/index.js) and [v5.0.0](https://github.com/jantimon/html-webpack-plugin/blob/v5.0.0/index.js). They seem the same.

**Comment by wangzhengbo** [comment]
> Hi, I'm not sure what the difference is between the constructor for [v5.54](https://github.com/jantimon/html-webpack-plugin/blob/v5.5.4/index.js) and [v5.0.0](https://github.com/jantimon/html-webpack-plugin/blob/v5.0.0/index.js). They seem the same.

In html-webpack-plugin <= 5.5.3, this.options is inited in apply method, but in version 5.5.4, this.options is inited in constructor like this: this.options = Object.assign(defaultOptions, this.userOptions);

react-app-rewire-html-webpack-plugin will update this.userOptions after this.options inited.

// Before 5.5.4
react-app-rewire-html-webpack-plugin update userOptions, then
html-webpack-plugin init options based on userOptions

// 5.5.4
html-webpack-plugin init options based on userOptions, then
react-app-rewire-html-webpack-plugin update userOptions

**Comment by Cheng0639** [comment]
Hi, I changed the way to determine which key to modify.  thx.

**Comment by wangzhengbo** [comment]
> Hi, I changed the way to determine which key to modify. thx.

After upgrade to react-app-rewire-html-webpack-plugin 1.2.0, there's another error:

Error: Cannot find module '/s
ource/node_modules/html-webpack-plugin/package.json'
Require stack:
/source/node_modules/.pnpm/react-app-rewire-html-webpack-plugin@1.2.0_html-webpack-plugin@5.6.0_@rspack+core@0.7.1_@swc+_uhj63qyo4cxlbqsewvqmdtfsd4/node_modules/react-app-rewire-html-webpack-plugin/index.js

**Comment by wangzhengbo** [comment]
Change

const packageJson = require(path.resolve(
     'node_modules/html-webpack-plugin/package.json'
))

to

const packageJson = require('html-webpack-plugin/package.json')

will work.

**Comment by wangzhengbo** [comment]
Change

require(path.resolve(
  'node_modules/html-webpack-plugin/package.json'
))

to

require('html-webpack-plugin/package.json')

will work.

**Comment by Cheng0639** [comment]
Thanks for the correction.
